### ISSUE TITLE
Memory leak of MainViewModel

### ISSUE THREAD

**Issue by p26432** [JohannBlake/Jetmagic#3]
LeakCanary reports that the static var mainViewModel: MainViewModel in the Application class is leaked after ViewModel.onCleared() is invoked.

**Comment by JohannBlake** [comment]
onCleared is not used anywhere in the app.

**Comment by JohannBlake** [comment]
onCleared is not called because that is called in ViewModelStore. ViewModelStore is a class used by Android for managing instances of viewmodels and will call onCleared when the viewmodel is no longer needed.

Jetmagic manages its own viewmodels and doesn't rely on the ViewModelStore. A viewmodel managed by Jetmagic is released for garbage collection whenever the screen that the viewmodel is associated with is no longer on the navigation stack. The exception to this is if you decide to cache the viewmodel permanently. When cached, even when the screen that is associated with the viewmodel is destroyed, the viewmodel remains in the cache and can be reused when the screen is displayed again.

The onCleared callback is generally used to allow your app to do any cleanup work prior to the viewmodel being released. With Jetmagic, you can accomplish the same thing if your viewmodel class implements the NavigationManagerHelper interface. When the user returns to the previous screen or navigates to the home screen, the onNavigateBack callback will get called, where you can do your cleanup work. So in essence, onNavigateBack performs the same function as onCleared.

**Comment by p26432** [comment]
I replied to the content of your first two emails before I noticed there
was a 3rd email in the batch.

The last instance of MainViewModel() that's assigned to the var
mainViewModel in the App() class doesn't get garbage-collected since it's a
static variable and won't go away until the entire application is removed
from memory by the OS.

**Comment by JohannBlake** [comment]
Keeping the viewmodel for the home screen (MainViewModel) cached even when the user exits the app was done by design. It often happens that a user will be using an app and navigate to several screens and then hit the Back button successively until they reach the home screen. But sometimes a user will hit the Back button rather quickly and end up hitting it on the home screen, causing the app to exit (but not terminate). When the user realizes they hit the Back button one too many times, they just start the app again and hope to carry on from where they left off on the home screen without losing any state.

This of course is a design choice by developers and some may want to opt for having the app start from a fresh starting point when the main activity is restarted. If this is an issue, I could add an optional feature that releases the viewmodel on the home screen when the user hits the Back button. The developer however can still choose to just create viewmodels the way they normally do without Jetmagic managing them and they will get cleaned up when the activity is stopped. With Jetmagic, it's not an "all or nothing". You can have Jetmagic manage the viewmodels for some screens while you use traditional viewmodel management for other screens.

**Comment by p26432** [comment]
My 2-pfennigen is to add the option to not have Jetmagic cache the
viewmodels it controls. At a minimum the fact that Jetmagic does caching
should be documented so developers aren't surprised when they go looking
for memory leaks in their Jetmagic app.

Based on the reports from LeakCanary, the leaking of the home screen view
model went away when I nulled out the mainViewModel companion object
defined in App(). Thus, this leak already seems to be completely in the
hands of the developer.  On the other hand, the leaking of NavViewModel
seems to be under the control of Jetmagic.

**Comment by JohannBlake** [comment]
You wrote:

>"My 2-pfennigen is to add the option to not have Jetmagic cache the viewmodels it controls."

There are two types of caches in Jetmagic for viewmodels. When you request Jetmagic to manage your viewmodel when you add a composable resource using addComposableResources, these viewmodels are transient. You are not required to provide a viewmodel. As soon as the screen is no longer available, these viewmodels are released. The exception, as noted, is the home screen, which retains this in the event the user restarts the app and wants their screen state restored. The other cache is the permanent cache that you can optionally request when you navigate with the ```goto```` function. When a viewmodel is placed in this permanent cache, it remains there for the entire lifecycle of the app and can only be removed when you call ```goBack``` to return to a previous screen (or call ```gotoHomeScreen``` and request that it be removed. The caching of viewmodels is documented.

Maybe what you are requesting is to not have the viewmodel for the home screen permanently cached by default and only permanently cache it when the user requests it? 

You wrote:

> "the leaking of NavViewModel seems to be under the control of Jetmagic"

I believe you are referring to the ```NavDrawerViewModel``` as there is no ```NavViewModel```. ```NavDrawerViewModel``` is however under the control of the developer and not Jetmagic.

**Comment by p26432** [comment]
Yes, I did mean the NavDrawerViewModel.

I didn't realize I controlled the caching of the NavDrawerViewModel. This
means I'm in control of all the leaks reported by LeakCanary and it no
longer makes sense to add a "no-caching" option. I'm sorry for wasting so
much of your time on this issue.

**Comment by JohannBlake** [comment]
I probably should fix the demo app anyway so that others don't make the same mistake and see a memory leak, thinking it originates in Jetmagic.

**Comment by p26432** [comment]
Sounds good to me!
